/**
 * @module Effect/IConfigurationService/Bridge/UserSettingsBridgeShapeGenerated
 * @description
 * Generated by Wind/Codegen from
 * vs/platform/configuration/common/configuration.ts:14
 * (decorator tag "configurationService").
 * Pick<…> over the upstream schema is the structural source
 * of truth for the bridge. The Live layer imports this type
 * and any upstream rename surfaces as a TypeScript build
 * error.
 * DO NOT EDIT BY HAND.
 * @category Generated
 */

import type { IConfigurationServiceUpstream } from "../../Generated/IConfigurationService/IConfigurationServiceUpstream.js";

export type UserSettingsBridgeShape = Pick<IConfigurationServiceUpstream, "getValue" | "updateValue" | "inspect" | "onDidChangeConfiguration">;

export interface UserSettingsGlobals {

	readonly __CEL_SERVICES__?: {
		readonly Configuration?: UserSettingsBridgeShape | null;
	};
}
