/**
 * @module Codegen/Emit/EmitServiceCatalog
 * @description
 * Catalog emitter - writes a single `ServiceCatalog.ts` to
 * `Wind/Source/Effect/Generated/ServiceCatalog.ts` containing one
 * entry per discovered decorator. Wind code that wants to enumerate
 * the surface (Phase-2 batch progress dashboard, audit scripts,
 * the LandWorkbench registry autoloader) imports the catalog
 * once and iterates.
 *
 * The catalog is the only file the rest of Wind ever needs to
 * reach for "what services exist in upstream". Per-service schema
 * files are referenced by the catalog and `import type`-able by
 * any bridge module.
 * @category Emit
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CodegenProblem } from "../Type/CodegenProblem.js";
import type { ServiceDecoratorRecord } from "../Type/ServiceDecoratorRecord.js";

export interface ServiceCatalogEntryEmit {
	readonly DecoratorName: string;

	readonly DecoratorTag: string;

	readonly InterfaceName: string;

	readonly SourcePath: string;

	readonly SourceLine: number;

	readonly MemberCount: number;
}

export interface EmitServiceCatalogOptions {
	readonly Records: ReadonlyArray<ServiceDecoratorRecord>;

	readonly OutputRoot: string;
}

export interface EmitServiceCatalogOutcome {
	readonly OutputPath: string;

	readonly Bytes: number;

	readonly Entries: number;
}

const FormatEntry = (
	entry: ServiceCatalogEntryEmit,

	index: number,

	total: number,
): string => {
	const Trailing = index === total - 1 ? "" : ",";

	return [
		`	{`,

		`		DecoratorName: ${JSON.stringify(entry.DecoratorName)},`,

		`		DecoratorTag: ${JSON.stringify(entry.DecoratorTag)},`,

		`		InterfaceName: ${JSON.stringify(entry.InterfaceName)},`,

		`		SourcePath: ${JSON.stringify(entry.SourcePath)},`,

		`		SourceLine: ${entry.SourceLine},`,

		`		MemberCount: ${entry.MemberCount},`,

		`	}${Trailing}`,
	].join("\n");
};

const FormatOutput = (
	records: ReadonlyArray<ServiceDecoratorRecord>,
): string => {
	const Sorted = [...records].sort((a, b) =>
		a.DecoratorName.localeCompare(b.DecoratorName),
	);

	const Entries: ReadonlyArray<ServiceCatalogEntryEmit> = Sorted.map(
		(record) => ({
			DecoratorName: record.DecoratorName,
			DecoratorTag: record.DecoratorTag,
			InterfaceName: record.InterfaceName,
			SourcePath: record.SourcePath,
			SourceLine: record.SourceLine,
			MemberCount: record.Members.length,
		}),
	);

	const Body = Entries.map((entry, index) =>
		FormatEntry(entry, index, Entries.length),
	).join("\n");

	const Header = [
		"/**",

		" * @module Effect/Generated/ServiceCatalog",

		" * @description",

		" * Generated by Wind/Codegen. Lists every `createDecorator` call",

		" * site found in the VS Code source tree at codegen time.",

		" * Per-service schema files live under",

		" * `Effect/Generated/<DecoratorName>/<DecoratorName>Upstream.ts`",

		" * and are imported by the manually-authored Wind bridge shapes.",

		" * DO NOT EDIT BY HAND.",

		" * @category Generated",

		" */",

		"",

		"export interface ServiceCatalogEntry {",

		"	readonly DecoratorName: string;",

		"	readonly DecoratorTag: string;",

		"	readonly InterfaceName: string;",

		"	readonly SourcePath: string;",

		"	readonly SourceLine: number;",

		"	readonly MemberCount: number;",

		"}",

		"",

		`export const ServiceCatalogVersion = ${JSON.stringify(
			new Date().toISOString().slice(0, 10),
		)} as const;`,

		"",

		`export const ServiceCatalogTotal = ${Entries.length} as const;`,

		"",

		"export const ServiceCatalog: ReadonlyArray<ServiceCatalogEntry> = [",
	];

	const Footer = ["] as const;", ""];

	return [...Header, Body, ...Footer].join("\n");
};

export const EmitServiceCatalog = async (
	options: EmitServiceCatalogOptions,
): Promise<EmitServiceCatalogOutcome | CodegenProblem> => {
	const Output = FormatOutput(options.Records);

	const OutputPath = join(
		options.OutputRoot,

		"Effect",

		"Generated",

		"ServiceCatalog.ts",
	);

	try {
		await mkdir(dirname(OutputPath), { recursive: true });

		await writeFile(OutputPath, Output, "utf8");

		return {
			OutputPath,

			Bytes: Buffer.byteLength(Output),

			Entries: options.Records.length,
		};
	} catch (Cause) {
		return {
			_tag: "CodegenEmitFailed",

			path: OutputPath,

			error: Cause instanceof Error ? Cause : new Error(String(Cause)),
		};
	}
};

export default EmitServiceCatalog;
