/**
 * @module Codegen/Emit/EmitCommandCatalog
 * @description
 * Catalog emitter - writes a single
 * `Effect/Generated/CommandCatalog.ts` to Wind's source tree, listing
 * every `CommandsRegistry.registerCommand(...)` /
 * `KeybindingsRegistry.registerCommandAndKeybindingRule(...)` /
 * `MenuRegistry.appendMenuItem(...)` call site discovered by
 * `IterateCommandRegistrations`. The catalog feeds two consumers:
 *
 *   1. The smoke-test harness (`SmokeTest/CommandCatalog.ts`) -
 *      Wind/Sky boots up, walks the catalog, asserts each id is
 *      callable through `vscode.commands.executeCommand` (return
 *      value is intentionally unobserved; the harness only checks
 *      that the call doesn't throw a `command_not_found`).
 *   2. The dual-track router - Mountain's command registry can use
 *      the catalog to detect upstream commands that are registered
 *      twice (Rust handler + lifted JS) and decide which surface
 *      to delegate to.
 *
 * Catalog is sorted by `CommandIdentifier` so diffs across runs
 * stay reviewable.
 *
 * @category Emit
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CodegenProblem } from "../Type/CodegenProblem.js";
import type { CommandRegistrationRecord } from "../Type/CommandRegistrationRecord.js";

export interface EmitCommandCatalogOptions {
	readonly Records: ReadonlyArray<CommandRegistrationRecord>;
	readonly OutputRoot: string;
}

export interface EmitCommandCatalogOutcome {
	readonly OutputPath: string;
	readonly Bytes: number;
	readonly Entries: number;
}

const FormatEntry = (
	entry: CommandRegistrationRecord,
	index: number,
	total: number,
): string => {
	const Trailing = index === total - 1 ? "" : ",";
	return [
		`\t{`,
		`\t\tCommandIdentifier: ${JSON.stringify(entry.CommandIdentifier)},`,
		`\t\tKind: ${JSON.stringify(entry.Kind)},`,
		`\t\tSourcePath: ${JSON.stringify(entry.SourcePath)},`,
		`\t\tSourceLine: ${entry.SourceLine},`,
		`\t\tHasKeybinding: ${entry.HasKeybinding ? "true" : "false"},`,
		`\t}${Trailing}`,
	].join("\n");
};

const FormatOutput = (
	records: ReadonlyArray<CommandRegistrationRecord>,
): string => {
	// De-duplicate while preserving the *first* registration site we
	// saw (which is the canonical one in stock VS Code; secondary
	// `registerCommand` calls are usually re-registrations from
	// extension-host shims or test fixtures).
	const Seen = new Set<string>();
	const Filtered: CommandRegistrationRecord[] = [];
	for (const Record of records) {
		if (Seen.has(Record.CommandIdentifier)) continue;
		Seen.add(Record.CommandIdentifier);
		Filtered.push(Record);
	}
	const Sorted = [...Filtered].sort((a, b) =>
		a.CommandIdentifier.localeCompare(b.CommandIdentifier),
	);
	const Body = Sorted.map((entry, index) =>
		FormatEntry(entry, index, Sorted.length),
	).join("\n");
	const Header = [
		"/**",
		" * @module Effect/Generated/CommandCatalog",
		" * @description",
		" * Generated by Wind/Codegen. Lists every command registration",
		" * call site found in the VS Code source tree at codegen time.",
		" * Used by the Wind/Sky smoke-test harness and Mountain's",
		" * command-registry dual-track router.",
		" * DO NOT EDIT BY HAND.",
		" * @category Generated",
		" */",
		"",
		"export type CommandRegistrationKind =",
		'\t| "CommandsRegistry"',
		'\t| "KeybindingsRegistry"',
		'\t| "MenuRegistry"',
		'\t| "ActionDescriptor";',
		"",
		"export interface CommandCatalogEntry {",
		"\treadonly CommandIdentifier: string;",
		"\treadonly Kind: CommandRegistrationKind;",
		"\treadonly SourcePath: string;",
		"\treadonly SourceLine: number;",
		"\treadonly HasKeybinding: boolean;",
		"}",
		"",
		`export const CommandCatalogVersion = ${JSON.stringify(
			new Date().toISOString().slice(0, 10),
		)} as const;`,
		"",
		`export const CommandCatalogTotal = ${Sorted.length} as const;`,
		"",
		"export const CommandCatalog: ReadonlyArray<CommandCatalogEntry> = [",
	];
	const Footer = ["] as const;", ""];
	return [...Header, Body, ...Footer].join("\n");
};

export const EmitCommandCatalog = async (
	options: EmitCommandCatalogOptions,
): Promise<EmitCommandCatalogOutcome | CodegenProblem> => {
	const Output = FormatOutput(options.Records);
	const OutputPath = join(
		options.OutputRoot,
		"Effect",
		"Generated",
		"CommandCatalog.ts",
	);
	try {
		await mkdir(dirname(OutputPath), { recursive: true });
		await writeFile(OutputPath, Output, "utf8");
		return {
			OutputPath,
			Bytes: Buffer.byteLength(Output),
			Entries: options.Records.length,
		};
	} catch (Cause) {
		return {
			_tag: "CodegenEmitFailed",
			path: OutputPath,
			error: Cause instanceof Error ? Cause : new Error(String(Cause)),
		};
	}
};

export default EmitCommandCatalog;
