/**
 * @module Codegen/Emit/EmitServiceSchema
 * @description
 * Per-service schema emitter. Takes a `ServiceDecoratorRecord` and
 * writes a typed `<Service>Upstream.ts` file under
 * `Wind/Source/Effect/Generated/<Decorator>/<Decorator>Upstream.ts`.
 *
 * The emitted file is pure types: no runtime code. It encodes the
 * upstream interface as a `interface <Name>Upstream { … }`
 * declaration plus a const record listing every member with kind,
 * parameter signatures, return type, and source location. The
 * Wind-side bridge shapes (`<Service>BridgeShape.ts`) `import type`
 * from the generated file so an upstream API change surfaces as a
 * type error in the manually-authored bridge.
 *
 * The emitter is idempotent. Running codegen on an unchanged
 * source tree produces byte-identical output. Diff-friendly
 * formatting: members sorted by source line, JSDoc preserved
 * verbatim.
 * @category Emit
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CodegenProblem } from "../Type/CodegenProblem.js";
import type {
	InterfaceMemberParameter,
	InterfaceMemberRecord,
} from "../Type/InterfaceMemberRecord.js";
import type { ServiceDecoratorRecord } from "../Type/ServiceDecoratorRecord.js";

const FormatDocComment = (doc: string | null, indent: string): string => {
	if (!doc) return "";

	const Lines = doc.split(/\r?\n/);

	const Body = Lines.map((line) => `${indent} * ${line}`.trimEnd()).join(
		"\n",
	);

	return `${indent}/**\n${Body}\n${indent} */\n`;
};

const FormatParameter = (parameter: InterfaceMemberParameter): string =>
	`${parameter.Name}${parameter.Optional ? "?" : ""}: ${parameter.TypeText}`;

const FormatMember = (member: InterfaceMemberRecord): string => {
	const Doc = FormatDocComment(member.DocComment, "	");

	const ReadonlyPrefix = member.Readonly ? "readonly " : "";

	const OptionalSuffix = member.Optional ? "?" : "";

	if (member.Kind === "Method") {
		const Parameters = member.Parameters.map(FormatParameter).join(", ");

		return `${Doc}	${ReadonlyPrefix}${member.Name}${OptionalSuffix}(${Parameters}): ${member.TypeText};`;
	}

	return `${Doc}	${ReadonlyPrefix}${member.Name}${OptionalSuffix}: ${member.TypeText};`;
};

const FormatMemberRecord = (
	member: InterfaceMemberRecord,

	index: number,

	total: number,
): string => {
	const Parameters = member.Parameters.map(
		(parameter) =>
			`{ Name: ${JSON.stringify(parameter.Name)}, TypeText: ${JSON.stringify(parameter.TypeText)}, Optional: ${parameter.Optional} }`,
	).join(", ");

	const DocText = member.DocComment
		? JSON.stringify(member.DocComment)
		: "null";

	const Trailing = index === total - 1 ? "" : ",";

	return [
		`	{`,

		`		Kind: "${member.Kind}",`,

		`		Name: ${JSON.stringify(member.Name)},`,

		`		Readonly: ${member.Readonly},`,

		`		Optional: ${member.Optional},`,

		`		TypeText: ${JSON.stringify(member.TypeText)},`,

		`		Parameters: [${Parameters}],`,

		`		DocComment: ${DocText},`,

		`		SourceLine: ${member.SourceLine},`,

		`	}${Trailing}`,
	].join("\n");
};

const Header = (record: ServiceDecoratorRecord): string => {
	const Generated = `Generated by Wind/Codegen from ${record.SourcePath}:${record.SourceLine}.\nDecorator tag: ${JSON.stringify(record.DecoratorTag)}.\nDO NOT EDIT BY HAND. Re-run codegen to refresh.`;

	const Doc = FormatDocComment(Generated, "");

	return Doc;
};

export interface EmitServiceSchemaOptions {
	readonly Record: ServiceDecoratorRecord;

	readonly OutputRoot: string;
}

export interface EmitServiceSchemaOutcome {
	readonly OutputPath: string;

	readonly Bytes: number;

	readonly Members: number;
}

const FormatOutput = (record: ServiceDecoratorRecord): string => {
	const SortedMembers = [...record.Members].sort(
		(a, b) => a.SourceLine - b.SourceLine,
	);

	const InterfaceBody =
		SortedMembers.length === 0
			? "	// (no members extracted in same file - resolve cross-file)"
			: SortedMembers.map(FormatMember).join("\n");

	const RecordList =
		SortedMembers.length === 0
			? ""
			: SortedMembers.map((member, index) =>
					FormatMemberRecord(member, index, SortedMembers.length),
				).join("\n");

	const InterfaceDoc = FormatDocComment(record.InterfaceDocComment, "");

	const DecoratorDoc = FormatDocComment(record.DecoratorDocComment, "");

	const InterfaceTypeName = `${record.DecoratorName}Upstream`;

	const Body = [
		Header(record),

		"",

		`import type { InterfaceMemberRecord } from "../../Codegen/Type/InterfaceMemberRecord.js";`,

		"",

		`export const ${record.DecoratorName}Tag = ${JSON.stringify(record.DecoratorTag)} as const;`,

		`export const ${record.DecoratorName}SourcePath = ${JSON.stringify(record.SourcePath)} as const;`,

		`export const ${record.DecoratorName}SourceLine = ${record.SourceLine} as const;`,

		"",

		DecoratorDoc.length > 0
			? `// Decorator doc:\n${DecoratorDoc.split("\n")
					.map((line) => `// ${line}`)
					.join("\n")}`
			: "",

		"",

		InterfaceDoc.length > 0 ? InterfaceDoc : "",

		`export interface ${InterfaceTypeName} {`,

		InterfaceBody,

		"}",

		"",

		`export const ${record.DecoratorName}Members: ReadonlyArray<InterfaceMemberRecord> = [`,

		RecordList,

		"] as const;",

		"",
	];

	return (
		Body.filter((part) => part !== "")
			.join("\n")
			.trim() + "\n"
	);
};

export const EmitServiceSchema = async (
	options: EmitServiceSchemaOptions,
): Promise<EmitServiceSchemaOutcome | CodegenProblem> => {
	const Output = FormatOutput(options.Record);

	const Folder = join(
		options.OutputRoot,

		"Effect",

		"Generated",

		options.Record.DecoratorName,
	);

	const OutputPath = join(
		Folder,

		`${options.Record.DecoratorName}Upstream.ts`,
	);

	try {
		await mkdir(dirname(OutputPath), { recursive: true });

		await writeFile(OutputPath, Output, "utf8");

		return {
			OutputPath,

			Bytes: Buffer.byteLength(Output),

			Members: options.Record.Members.length,
		};
	} catch (Cause) {
		return {
			_tag: "CodegenEmitFailed",

			path: OutputPath,

			error: Cause instanceof Error ? Cause : new Error(String(Cause)),
		};
	}
};

export default EmitServiceSchema;
