/**
 * @module Codegen/Emit/EmitBridgeShape
 * @description
 * Generates a `Workbench<X>BridgeShape.ts` file alongside each
 * service's hand-authored Implementation/, deriving the upstream-
 * grounded shape from the codegen-emitted `<Decorator>Upstream`
 * interface as a `Pick<…Upstream, "method1" | "method2">`.
 *
 * The intent is to eliminate the hand-maintained
 * `Workbench<X>BridgeShape.ts` files and have them be a one-line
 * `Pick<…>` over the generated upstream schema. The
 * Implementation/Live consumes the typed shape through `import type`
 * so any upstream rename / removal surfaces as a TypeScript build
 * error in the Live layer.
 *
 * Idempotent. Re-running the emit on an unchanged
 * `ServiceDecoratorRecord` produces byte-identical output.
 * @category Emit
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CodegenProblem } from "../Type/CodegenProblem.js";
import type { ServiceDecoratorRecord } from "../Type/ServiceDecoratorRecord.js";

export interface EmitBridgeShapeOptions {
	/** Decorator record from `IterateServiceDecorators`. */
	readonly Record: ServiceDecoratorRecord;
	/** Member names that the Wind bridge actually consumes. Empty
	 * picks every member. Use this to scope the bridge's surface
	 * down to what the Live layer needs.
	 */
	readonly PickMembers: ReadonlyArray<string>;
	/** Wind's `Source/` directory. */
	readonly OutputRoot: string;
	/** Wind subfolder under `Effect/` to land the bridge in
	 * (`Workbench<X>` for the workbench-tier services).
	 */
	readonly ServiceFolder: string;
	/** Filename without extension. Defaults to
	 * `<ServiceFolder>BridgeShape`.
	 */
	readonly BridgeFileName?: string;
}

export interface EmitBridgeShapeOutcome {
	readonly OutputPath: string;
	readonly Bytes: number;
	readonly PickedMembers: ReadonlyArray<string>;
}

const FormatPickUnion = (members: ReadonlyArray<string>): string => {
	if (members.length === 0) return "never";
	return members.map((m) => JSON.stringify(m)).join(" | ");
};

const FormatOutput = (
	record: ServiceDecoratorRecord,
	pickedMembers: ReadonlyArray<string>,
	bridgeFileName: string,
): string => {
	const UpstreamModule = `../../Generated/${record.DecoratorName}/${record.DecoratorName}Upstream.js`;
	const UpstreamType = `${record.DecoratorName}Upstream`;
	const PickClause = FormatPickUnion(pickedMembers);
	const ShapeName = bridgeFileName.replace(/Shape$/, "Shape");
	return [
		"/**",
		` * @module Effect/${record.DecoratorName}/Bridge/${bridgeFileName}`,
		" * @description",
		` * Generated by Wind/Codegen from`,
		` * ${record.SourcePath}:${record.SourceLine}`,
		` * (decorator tag ${JSON.stringify(record.DecoratorTag)}).`,
		" * Pick<…> over the upstream schema is the structural source",
		" * of truth for the bridge. The Live layer imports this type",
		" * and any upstream rename surfaces as a TypeScript build",
		" * error.",
		" * DO NOT EDIT BY HAND.",
		" * @category Generated",
		" */",
		"",
		`import type { ${UpstreamType} } from "${UpstreamModule}";`,
		"",
		`export type ${ShapeName} = Pick<${UpstreamType}, ${PickClause}>;`,
		"",
		`export interface ${record.DecoratorName}Globals {`,
		"\treadonly __CEL_SERVICES__?: {",
		`\t\treadonly ${record.DecoratorName.replace(/^I/, "")}?: ${ShapeName} | null;`,
		"\t};",
		"}",
		"",
	].join("\n");
};

export const EmitBridgeShape = async (
	options: EmitBridgeShapeOptions,
): Promise<EmitBridgeShapeOutcome | CodegenProblem> => {
	const ResolvedPicks =
		options.PickMembers.length === 0
			? options.Record.Members.map((m) => m.Name)
			: options.PickMembers;

	const FileName =
		options.BridgeFileName ?? `${options.ServiceFolder}BridgeShape`;

	const Output = FormatOutput(options.Record, ResolvedPicks, FileName);
	const OutputPath = join(
		options.OutputRoot,
		"Effect",
		options.ServiceFolder,
		"Implementation",
		`${FileName}.ts`,
	);
	try {
		await mkdir(dirname(OutputPath), { recursive: true });
		await writeFile(OutputPath, Output, "utf8");
		return {
			OutputPath,
			Bytes: Buffer.byteLength(Output),
			PickedMembers: ResolvedPicks,
		};
	} catch (Cause) {
		return {
			_tag: "CodegenEmitFailed",
			path: OutputPath,
			error: Cause instanceof Error ? Cause : new Error(String(Cause)),
		};
	}
};

export default EmitBridgeShape;
