/**
 * @module Codegen/Emit/EmitBridgeShape
 * @description
 * Generates a `Workbench<X>BridgeShape.ts` file alongside each
 * service's hand-authored Implementation/, deriving the upstream-
 * grounded shape from the codegen-emitted `<Decorator>Upstream`
 * interface as a `Pick<…Upstream, "method1" | "method2">`.
 *
 * The intent is to eliminate the hand-maintained
 * `Workbench<X>BridgeShape.ts` files and have them be a one-line
 * `Pick<…>` over the generated upstream schema. The
 * Implementation/Live consumes the typed shape through `import type`
 * so any upstream rename / removal surfaces as a TypeScript build
 * error in the Live layer.
 *
 * Idempotent. Re-running the emit on an unchanged
 * `ServiceDecoratorRecord` produces byte-identical output.
 * @category Emit
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CodegenProblem } from "../Type/CodegenProblem.js";
import type { ServiceDecoratorRecord } from "../Type/ServiceDecoratorRecord.js";

export interface EmitBridgeShapeOptions {
	/** Decorator record from `IterateServiceDecorators`. */
	readonly Record: ServiceDecoratorRecord;

	/** Member names that the Wind bridge actually consumes. Empty
	 * picks every member. Use this to scope the bridge's surface
	 * down to what the Live layer needs.
	 */
	readonly PickMembers: ReadonlyArray<string>;

	/** Wind's `Source/` directory. */
	readonly OutputRoot: string;

	/** Wind subfolder under `Effect/` to land the bridge in
	 * (`Workbench<X>` for the workbench-tier services).
	 */
	readonly ServiceFolder: string;

	/** Filename without extension. Defaults to
	 * `<ServiceFolder>BridgeShape`.
	 */
	readonly BridgeFileName?: string;

	/** Override the `__CEL_SERVICES__` accessor key. Defaults to
	 * `decoratorName.replace(/^I/, "")`. Set to align with the
	 * actual Output binding (e.g. `Clipboard` for `IClipboardService`).
	 */
	readonly AccessorName?: string;

	/** Override the exported Globals interface name. Defaults to
	 * `<decoratorName>Globals`.
	 */
	readonly GlobalsInterfaceName?: string;

	/** Override the exported Pick<> type alias name. Defaults to
	 * `BridgeFileName` with any trailing `Generated` suffix stripped.
	 */
	readonly ShapeTypeName?: string;
}

export interface EmitBridgeShapeOutcome {
	readonly OutputPath: string;

	readonly Bytes: number;

	readonly PickedMembers: ReadonlyArray<string>;
}

const FormatPickUnion = (members: ReadonlyArray<string>): string => {
	if (members.length === 0) return "never";

	return members.map((m) => JSON.stringify(m)).join(" | ");
};

const FormatOutput = (
	record: ServiceDecoratorRecord,

	pickedMembers: ReadonlyArray<string>,

	bridgeFileName: string,

	accessorName: string,

	globalsInterfaceName: string,

	shapeTypeName: string,
): string => {
	const UpstreamModule = `../../Generated/${record.DecoratorName}/${record.DecoratorName}Upstream.js`;

	const UpstreamType = `${record.DecoratorName}Upstream`;

	const PickClause = FormatPickUnion(pickedMembers);

	return [
		"/**",
		` * @module Effect/${record.DecoratorName}/Bridge/${bridgeFileName}`,
		" * @description",
		` * Generated by Wind/Codegen from`,
		` * ${record.SourcePath}:${record.SourceLine}`,
		` * (decorator tag ${JSON.stringify(record.DecoratorTag)}).`,
		" * Pick<…> over the upstream schema is the structural source",
		" * of truth for the bridge. The Live layer imports this type",
		" * and any upstream rename surfaces as a TypeScript build",
		" * error.",
		" * DO NOT EDIT BY HAND.",
		" * @category Generated",
		" */",
		"",

		`import type { ${UpstreamType} } from "${UpstreamModule}";`,

		"",

		`export type ${shapeTypeName} = Pick<${UpstreamType}, ${PickClause}>;`,

		"",

		`export interface ${globalsInterfaceName} {`,

		"	readonly __CEL_SERVICES__?: {",

		`		readonly ${accessorName}?: ${shapeTypeName} | null;`,

		"	};",

		"}",

		"",
	].join("\n");
};

export const EmitBridgeShape = async (
	options: EmitBridgeShapeOptions,
): Promise<EmitBridgeShapeOutcome | CodegenProblem> => {
	const ResolvedPicks =
		options.PickMembers.length === 0
			? options.Record.Members.map((m) => m.Name)
			: options.PickMembers;

	const FileName =
		options.BridgeFileName ?? `${options.ServiceFolder}BridgeShape`;

	// `ShapeTypeName` defaults to FileName with trailing `Generated`
	// stripped so the exported type is e.g. `WorkbenchClipboardBridgeShape`
	// even when the file is `WorkbenchClipboardBridgeShapeGenerated.ts`.
	// This lets the hand-authored `BridgeShape.ts` collapse to a one-line
	// `export type {...} from "./WorkbenchClipboardBridgeShapeGenerated.js"`.
	const ShapeTypeName =
		options.ShapeTypeName ?? FileName.replace(/Generated$/, "");

	// `AccessorName` defaults to `decoratorName.replace(/^I/, "")` for
	// backward-compat (so e.g. `IClipboardService` → `ClipboardService`).
	// Output's `ExposeWorkbenchAccessor` typically exposes a shorter
	// name (`Clipboard`); manifest entries opt in via `AccessorName`.
	const AccessorName =
		options.AccessorName ?? options.Record.DecoratorName.replace(/^I/, "");

	// `GlobalsInterfaceName` defaults to `<DecoratorName>Globals`. Set
	// to `Workbench<X>Globals` in manifest entries that want the
	// hand-authored layer to re-export both Shape + Globals together.
	const GlobalsInterfaceName =
		options.GlobalsInterfaceName ??
		`${options.Record.DecoratorName}Globals`;

	const Output = FormatOutput(
		options.Record,

		ResolvedPicks,

		FileName,

		AccessorName,

		GlobalsInterfaceName,

		ShapeTypeName,
	);

	const OutputPath = join(
		options.OutputRoot,

		"Effect",

		options.ServiceFolder,

		"Implementation",

		`${FileName}.ts`,
	);

	try {
		await mkdir(dirname(OutputPath), { recursive: true });

		await writeFile(OutputPath, Output, "utf8");

		return {
			OutputPath,

			Bytes: Buffer.byteLength(Output),

			PickedMembers: ResolvedPicks,
		};
	} catch (Cause) {
		return {
			_tag: "CodegenEmitFailed",

			path: OutputPath,

			error: Cause instanceof Error ? Cause : new Error(String(Cause)),
		};
	}
};

export default EmitBridgeShape;
